#!/usr/bin/env bash
# Runs once when the devcontainer is created.
# - provisions a Gurobi license (from benchmark/gurobi.lic and/or benchmark/.env)
# - creates the benchmark Python venv with `uv` (installs gurobipy + matplotlib)
# - builds a release HiGHS binary for benchmarking
set -euo pipefail

DEV_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BENCH_DIR="$DEV_ROOT/benchmark"

echo "==> Gurobi license provisioning"
mkdir -p "$HOME/.gurobi"

# 1) Local license file: benchmark/gurobi.lic  (or .devcontainer/gurobi.lic)
for f in "$BENCH_DIR/gurobi.lic" "$DEV_ROOT/.devcontainer/gurobi.lic"; do
  if [ -f "$f" ]; then
    cp "$f" "$HOME/.gurobi/gurobi.lic"
    echo "    installed license: $f"
    break
  fi
done

# 2) Environment-based license (WLS / named-user): benchmark/.env or ~/.env
#    Format: KEY=VALUE lines, e.g.
#      GRB_WLSACCESSID=...
#      GRB_WLSPASSWORD=...
#      GRB_LICENSEID=...
#      GUROBI_HOME=...
ENV_FILE="$BENCH_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
  echo "    sourced env from: $ENV_FILE"
fi

# Persist Gurobi/USERPROFILE env vars for all interactive shells
{
  echo "# generated by .devcontainer/postCreate.sh - Gurobi license env"
  env | grep -E '^(GRB_|GUROBI_|GRB_LICENSE)' | sed 's/^/export /' || true
} >> "$HOME/.bashrc"

echo "==> Python venv (uv)"
uv python install 3.12 || true
cd "$BENCH_DIR"
uv sync --frozen 2>/dev/null || uv sync

echo "==> Building HiGHS (release)"
"$BENCH_DIR/scripts/build_highs.sh"

echo "==> Done. Re-run '$BENCH_DIR/scripts/build_highs.sh' after editing HiGHS."
echo "    Validate Gurobi license with: $(uv run python -c 'import gurobipy as g; print(g.gurobi.version())' 2>/dev/null || echo 'see benchmark/README.md')"
